{"version":"3.7.1","messages":["\nAn error occurred while loading ./spec/no_ruby_errors_spec.rb.\n\u001b[31mFailure/Error:\u001b[0m\n\u001b[31m  \u001b[0m\u001b[32mbefore\u001b[0m{\u001b[0m\n\u001b[31m    \u001b[0mload \u001b[31m\u001b[1;31m'\u001b[0m\u001b[31m./lib/a_syntax_error.rb\u001b[1;31m'\u001b[0m\u001b[31m\u001b[0m\u001b[0m\n\u001b[31m  \u001b[0m}.to_not raise_error\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31m  `raise_error` is not available on an example group (e.g. a `describe` or `context` block). It is only available from within individual examples (e.g. `it` blocks) or from constructs that run in the scope of an example (e.g. `before`, `let`, etc).\u001b[0m\n\u001b[36m# ./spec/no_ruby_errors_spec.rb:15:in `block (2 levels) in <top (required)>'\u001b[0m\n\u001b[36m# ./spec/no_ruby_errors_spec.rb:11:in `block in <top (required)>'\u001b[0m\n\u001b[36m# ./spec/no_ruby_errors_spec.rb:1:in `<top (required)>'\u001b[0m\n"],"examples":[],"summary":{"duration":0.000350269,"example_count":0,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":1},"summary_line":"0 examples, 0 failures, 1 error occurred outside of examples"}